#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") [+F] [FILENAME]

'$(basename "$0")' uses 'vim' as a pager

The contents of FILENAME are shown.
The argument '+F' instructs '$(basename "$0")' to keep reading from
FILENAME. This behavior can be switched off in the program by pressing
'Ctrl-c', and switched on again by pressing 'F'.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

# Obain path to behold.vim
export BEHOLD_DIR="$(dirname $(readlink -f "$0"))"
vimScript="$BEHOLD_DIR/behold.vim"

follow=false
filename=

# numargs > 1
if [ "$#" -gt "1" ]; then
    if [ "$1" = "+F" ]; then
        follow=true
        filename="$2"
    else
        exitWith 1 "Unrecognized first argument: '$1'"
    fi

# numargs <= 1
else

    # numargs == 1
    if [ "$#" = 1 ]; then
        if [ "$1" = "+F" ]; then
            follow=true
        else
            filename="$1"
        fi
    fi
fi

if $follow; then
    followCommand="-c \"call StartTailing()\""
else
    followCommand=
fi

try test -n "$filename"

bash -c "vim -R -u $vimScript $followCommand $filename"
