#!/bin/bash

#[ -n "$LO_UTILS" ] && return || readonly LO_UTILS=1

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi


############################################################
#
# Get ID of the pane with the given title
#
# getPaneID PANE_TITLE
#
function getPaneID
{
    try test -n "$1"
    tmux list-panes -F "#{pane_id} #{pane_title}" | grep "$1" | cut -d ' ' -f 1
}


############################################################
#
# gotoPalico PATH [LINE [COLUMN]]
#
function gotoPalico
{
    local path="$1"
    local line="${2:-0}"
    local column="${3:-0}"

    if [ -n "$path" ]; then
        tmux send-keys -t $(getPaneID lo-edit) ":e $path|call cursor($line,$column)|norm zz" Enter
    fi
}

export -f getPaneID
export -f gotoPalico


