#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

scriptName=$(basename "$0")

function showHelp
{
cat << DOCSTRING
Usage: $scriptName
DOCSTRING
}

checkForHelp $1

nohup logop <&0  > /dev/null &
disown

#
if [ -z "$TMUX" ]; then
    exitWith 1 "ERROR: '$(basename "$0")' needs to be run inside 'tmux'"
fi

#tmux new-session -d "less +F ~/log/latest.txt"
tmux split-window -h -p 50

